services:
  migrate:
    image: ghcr.io/hampuslundblad/migrations:main
    volumes:
      - ./db/test.db:/app/test.db
    profiles:
      - migrate
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build: .
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./:/home/hampus/fullstack-osrs
      - /etc/letsencrypt/live/hampuslundblad.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/hampuslundblad.com/privkey.pem:/etc/nginx/ssl/privkey.pem

  backend:
    image: ghcr.io/hampuslundblad/backend_comp:main
    ports:
      - "5000:5000"
    volumes:
      - ./db/test.db:/app/test.db
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    env_file:
      - secrets.env
  frontend:
    image: ghcr.io/hampuslundblad/frontend_comp:main
    ports:
      - "3000:3000"
