services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build: .
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./:/home/hampus/fullstack-osrs
      - /etc/letsencrypt/live/hampuslundblad.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/hampuslundblad.com/privkey.pem:/etc/nginx/ssl/privkey.pem

  backend:
    image: hampuslundblad1/comp_backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ../backend/DotnetComp/test.db:/app/test.db
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    env_file:
      - secrets.env
  frontend:
    image: hampuslundblad1/comp_frontend:latest
    ports:
      - "3000:3000"
