# build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["DotnetComp.csproj", "./"]
RUN dotnet restore "DotnetComp.csproj"

COPY . .    
RUN dotnet publish -c Release -o /app

#runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
EXPOSE 8080
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "DotnetComp.dll"]
