services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --interval 30
    environment:
      WATCHTOWER_DISABLE_CONTAINERS: "fullstack-osrs-nginx-1"
      WATCHTOWER_CLEANUP: true
