# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Backend - Build & push container to GHCR

on:
  push:
    branches: main
    paths:
      - "backend/DotnetComp/**"
      - ".github/workflows/publish-backend-image.yaml"
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/reusable-publish-backend-image.yaml
    with:
      registry: ghcr.io
      image_name: hampuslundblad/backend_comp
      context: ./backend/DotnetComp
